# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update README

# This one triggers whenever we push changes to docs/ directory
on:
  push:
    branches:
      - master
    paths: 
      - '../Python/*.py'
      - '../CPP/*.cpp'
      - '../CSharp/*.cs'

jobs:
  update-readme: # 이름 자유 아무거나
    runs-on: ubuntu-latest
      steps:
        - name: Check out the repository
          uses: actions/checkout@v4

        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v44
          # with:
          #   since_last_remote_commit: true 

        - name: List all changed files
          env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          run: |
            for file in ${ALL_CHANGED_FILES}; do
              echo "$file was changed"
            done

        # - name: Run write_readme.py
        #   run: |
        #     python ../write_readme.py

        - name: Commit and Push Changes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@gmail.com"
            git add -A
            git commit -m "auto update README.md"
            git push origin main

            