# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update README

# This one triggers whenever we push changes to docs/ directory
on:
  push:
    paths:
      - 'example code/**'
    branches: [ main ]
  pull_request:    
    paths:
      - 'example code/**'
    branches: [ main ]

jobs:
  update-readme: 
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install flake8 pytest
          # if [ -f example_code/requirements.txt ]; then pip install -r example_code/requirements.txt; fi
          if [ -f "example_code/requirements.txt" ]; then
              echo "File exists"
              pip install -r "example_code/requirements.txt"
          else
              echo "File doesn't exist"
          fi

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        # REF: https://github.com/marketplace/actions/changed-files

      - name: Processing about changed files
        env:
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
          MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
          RENAMED_FILES: ${{ steps.changed-files.outputs.renamed_files }}
        run: |
          ADDED_FILES_LIST=()
          DELETED_FILES_LIST=()
          MODIFIED_FILES_LIST=()
          RENAMED_FILES_LIST=()

          echo "========== ADDED_FILES"
          for file in "${ADDED_FILES[@]}"; do
            echo "$file"
            ADDED_FILES_LIST+=("$file")
          done

          echo "========== DELETED_FILES"
          for file in "${DELETED_FILES[@]}"; do
            echo "$file"
            DELETED_FILES_LIST+=("$file")
          done

          echo "========== MODIFIED_FILES"
          for file in "${MODIFIED_FILES[@]}"; do
            echo "$file"
            MODIFIED_FILES_LIST+=("$file")
          done

          echo "========== RENAMED_FILES"
          for file in "${RENAMED_FILES[@]}"; do
            echo "$file"
            RENAMED_FILES_LIST+=("$file")
          done
          echo ""

          echo "Processing ..."
          python ./helpers/read_files.py "${ADDED_FILES_LIST[@]:-}" "${DELETED_FILES_LIST[@]:-}" "${MODIFIED_FILES_LIST[@]:-}" "${RENAMED_FILES_LIST[@]:-}"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}23@gmail.com"
          git add -A
          git commit -m "auto update README.md"
          git push origin main
            